# Generated by Django 2.0 on 2017-12-16 16:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171213_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pre_text',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
